apiVersion: v1
kind: Service
metadata:
  name: {{ include "botmux.fullname" . }}
  labels:
    {{- include "botmux.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "botmux.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
    - name: terminal
      port: {{ .Values.service.terminalPort }}
      targetPort: terminal
    {{- if .Values.dsh.web.enabled }}
    - name: dsh-web
      port: {{ .Values.dsh.web.port }}
      targetPort: dsh-web
    {{- end }}
